package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

var i = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

var e = `....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......`

var e1 = `....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
`

func TestTask1(t *testing.T) {
	got := task1(i)
	want := 374

	assert.Equal(t, want, got)
}

func TestTask2(t *testing.T) {

	got := task2(i)
	want := 82000210

	assert.Equal(t, want, got)
}

func TestParse(t *testing.T) {
	got := ToString(Parse(i, 2))
	want := e
	assert.Equal(t, want, got)
}

func TestDistance(t *testing.T) {
	g := Parse(i, 2)
	lo := FindGalaxies(g)
	d17 := CalculateDistance(lo[0][0], lo[0][1], lo[6][0], lo[6][1])
	d36 := CalculateDistance(lo[2][0], lo[2][1], lo[5][0], lo[5][1])
	d89 := CalculateDistance(lo[7][0], lo[7][1], lo[8][0], lo[8][1])

	wantd17 := 15
	wantd36 := 17
	wantd89 := 5

	assert.Equal(t, wantd17, d17)
	assert.Equal(t, wantd36, d36)
	assert.Equal(t, wantd89, d89)

}
